version: '3'
services:

    admin:
        container_name: newsadmin
        image: sabaedu0708/newsadmin
        restart: always
        ports:
          - "4400:4400"
        networks:
          - chayakada

    cust:
        container_name: newscust
        image: sabaedu0708/newscust
        restart: always
        ports:
          - "4401:4401"
        networks:
          - chayakada

    reverseproxy:
        container_name: news-nginx
        image: sabaedu/news-nginx
        ports:
          - "80:8080"
        networks:
          - chayakada

networks:
  chayakada:
    driver: bridge